### ISSUE TITLE
Suggestion: Allow opening of listed files via double click

### ISSUE THREAD

**Issue by bubbob42** [Arisamiga/Mnemosyne#10]
Implement opening of listed files via double click, so one could check the contents of the bloated discoveries. Using DefIcons of course. :)

Same functionality is present in OS3.2's "Find".

**Comment by Arisamiga** [comment]
> Implement opening of listed files via double click, so one could check the contents of the bloated discoveries. Using DefIcons of course. :)
> 
> Same functionality is present in OS3.2's "Find".

Thanks for creating an issue!

I don't quite understand what you mean by "check the contents of the bloated discoveries" 

There is something familiar in the Menu items called "Open in Workbench" which will open the folder on Workbench.

**Comment by bubbob42** [comment]
Hi! 

What I meant: with tools like Mnemosyne, you would usually hunt for large files (e.g. pictures) which you don’t need anymore. Before deleting it, one would like to preview/view its contents. Double clicking them inside the tool would feel natural for this purpose.

**Comment by Arisamiga** [comment]
> Hi!
> 
> What I meant: with tools like Mnemosyne, you would usually hunt for large files (e.g. pictures) that you don’t need anymore. Before deleting it, one would like to preview/view its contents. Double clicking them inside the tool would feel natural for this purpose.

Hello! Do you mean for example if it is a picture if you clicked on the file it would display the picture? 

In that case, I think it better to use the "Open in Workbench" as this would let you open the file yourself or open it with a different application of your choice and it would then allow you to remove it straight away because if you are hunting for large files you would open them in workbench to delete them.

**Comment by Arisamiga** [comment]
I am closing this Issue if you have any further issues or comments don't hesitate to reopen it! :D
